GROUP AND COUNT BY DEP I
                            
                            
-- QUERY 1 -- 
SELECT * FROM EMPLOYEES WHERE ADDRESS LIKE '%Elgin%';

-- QUERY 2 --
SELECT * FROM EMPLOYEES WHERE B_DATE LIKE '%197%';

--QUERY 3--
SELECT * FROM EMPLOYEES WHERE DEP_ID = 5 AND SALARY BETWEEN 60000 AND 70000;

-- QUERY 4--

SELECT * FROM EMPLOYEES ORDER BY DEP_ID;

-- QUERY 4B--
SELECT * FROM EMPLOYEES 
ORDER BY DEP_ID DESC, L_NAME DESC;

--QUERY 5A--

SELECT DEP_ID, COUNT(DEP_ID)  FROM EMPLOYEES GROUP BY DEP_ID;
                            
 -- QUERY 5B --
 SELECT DEP_ID, COUNT(*), AVG(SALARY) FROM EMPLOYEES GROUP BY DEP_ID;

-- QUERY 5C --
SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY" FROM EMPLOYEES GROUP BY DEP_ID;

-- QUERY 5D --
SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY" 
FROM EMPLOYEES 
GROUP BY DEP_ID
ORDER BY AVG_SALARY;

-- QUERY 5E --

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY" 
FROM EMPLOYEES 
GROUP BY DEP_ID
HAVING COUNT(*) < 4
ORDER BY AVG_SALARY;

-- TEST QUERY --
SELECT * FROM DEPARTMENTS;

-- QUERY 6 --
SELECT D.DEP_NAME, E.F_NAME, E.L_NAME 
FROM EMPLOYEES AS E, DEPARTMENTS AS D
WHERE E.DEP_ID = D.DEPT_ID_DEP
ORDER BY D.DEP_NAME, E.L_NAME DESC;

